project_name: thor
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: thor-build
    main: ./cmd/thor/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - ghcr.io/containeroo/thor:{{ trimprefix .Tag "v" }}-amd64
      - ghcr.io/containeroo/thor:latest-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/thor
      - --label=org.opencontainers.image.source=https://github.com/containeroo/thor
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
    extra_files:
      - go.mod
      - cmd
      - pkg
  - image_templates:
      - ghcr.io/containeroo/thor:{{ trimprefix .Tag "v" }}-arm64v8
      - ghcr.io/containeroo/thor:latest-arm64v8
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/thor
      - --label=org.opencontainers.image.source=https://github.com/containeroo/thor
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
    extra_files:
      - go.mod
      - cmd
      - pkg

docker_manifests:
  - name_template: ghcr.io/containeroo/thor:{{ trimprefix .Tag "v" }}
    image_templates:
      - ghcr.io/containeroo/thor:{{ trimprefix .Tag "v" }}-amd64
      - ghcr.io/containeroo/thor:{{ trimprefix .Tag "v" }}-arm64v8
  - name_template: ghcr.io/containeroo/thor:latest
    image_templates:
      - ghcr.io/containeroo/thor:latest-amd64
      - ghcr.io/containeroo/thor:latest-arm64v8
